/**
 * Static mapping from ITEMNAME.BIN indices to field_name identifiers and display names.
 *
 * ITEMNAME.BIN is the PS1 game's master item table. Each item has a fixed
 * index that never changes. This mapping is a game constant derived from
 * the extracted game data JSON files (which are in ITEMNAME.BIN order).
 *
 * The save file parser returns these indices. The save import mapper uses
 * this table to convert them to field_name strings, which the API endpoint
 * resolves to database records server-side.
 */

export type ImportItemType = "blade" | "grip" | "armor" | "gem" | "consumable"

export interface ItemNameEntry {
  type: ImportItemType
  fieldName: string
  /** Display name for UI preview (handles apostrophes, special cases) */
  name: string
}

/**
 * ITEMNAME.BIN index → { type, fieldName, name } for all importable item types.
 *
 * Ranges:
 *   1–90:    Blades
 *   96–126:  Grips
 *   128–207: Armor (Shields, Helms, Body, Legs, Arms)
 *   223–253: Accessories (stored in armor table)
 *   261–306: Gems
 *   323–360: Consumables
 */
// prettier-ignore
export const ITEMNAME_MAP: ReadonlyMap<number, ItemNameEntry> = new Map([
  // ── Blades: ITEMNAME 1–90 ─────────────────────────────────────────
  [1, { type: "blade", fieldName: "Battle_Knife", name: "Battle Knife" }],
  [2, { type: "blade", fieldName: "Scramasax", name: "Scramasax" }],
  [3, { type: "blade", fieldName: "Dirk", name: "Dirk" }],
  [4, { type: "blade", fieldName: "Throwing_Knife", name: "Throwing Knife" }],
  [5, { type: "blade", fieldName: "Kudi", name: "Kudi" }],
  [6, { type: "blade", fieldName: "Cinquedea", name: "Cinquedea" }],
  [7, { type: "blade", fieldName: "Kris", name: "Kris" }],
  [8, { type: "blade", fieldName: "Hatchet", name: "Hatchet" }],
  [9, { type: "blade", fieldName: "Khukuri", name: "Khukuri" }],
  [10, { type: "blade", fieldName: "Baselard", name: "Baselard" }],
  [11, { type: "blade", fieldName: "Stiletto", name: "Stiletto" }],
  [12, { type: "blade", fieldName: "Jamadhar", name: "Jamadhar" }],
  [13, { type: "blade", fieldName: "Spatha", name: "Spatha" }],
  [14, { type: "blade", fieldName: "Scimitar", name: "Scimitar" }],
  [15, { type: "blade", fieldName: "Rapier", name: "Rapier" }],
  [16, { type: "blade", fieldName: "Short_Sword", name: "Short Sword" }],
  [17, { type: "blade", fieldName: "Firangi", name: "Firangi" }],
  [18, { type: "blade", fieldName: "Shamshir", name: "Shamshir" }],
  [19, { type: "blade", fieldName: "Falchion", name: "Falchion" }],
  [20, { type: "blade", fieldName: "Shotel", name: "Shotel" }],
  [21, { type: "blade", fieldName: "Khora", name: "Khora" }],
  [22, { type: "blade", fieldName: "Khopesh", name: "Khopesh" }],
  [23, { type: "blade", fieldName: "Wakizashi", name: "Wakizashi" }],
  [24, { type: "blade", fieldName: "Rhomphaia", name: "Rhomphaia" }],
  [25, { type: "blade", fieldName: "Broad_Sword", name: "Broad Sword" }],
  [26, { type: "blade", fieldName: "Norse_Sword", name: "Norse Sword" }],
  [27, { type: "blade", fieldName: "Katana", name: "Katana" }],
  [28, { type: "blade", fieldName: "Executioner", name: "Executioner" }],
  [29, { type: "blade", fieldName: "Claymore", name: "Claymore" }],
  [30, { type: "blade", fieldName: "Schiavona", name: "Schiavona" }],
  [31, { type: "blade", fieldName: "Bastard_Sword", name: "Bastard Sword" }],
  [32, { type: "blade", fieldName: "Nodachi", name: "Nodachi" }],
  [33, { type: "blade", fieldName: "Rune_Blade", name: "Rune Blade" }],
  [34, { type: "blade", fieldName: "Holy_Win", name: "Holy Win" }],
  [35, { type: "blade", fieldName: "Hand_Axe", name: "Hand Axe" }],
  [36, { type: "blade", fieldName: "Battle_Axe", name: "Battle Axe" }],
  [37, { type: "blade", fieldName: "Francisca", name: "Francisca" }],
  [38, { type: "blade", fieldName: "Tabarzin", name: "Tabarzin" }],
  [39, { type: "blade", fieldName: "Chamkaq", name: "Chamkaq" }],
  [40, { type: "blade", fieldName: "Tabar", name: "Tabar" }],
  [41, { type: "blade", fieldName: "Bullova", name: "Bullova" }],
  [42, { type: "blade", fieldName: "Crescent", name: "Crescent" }],
  [43, { type: "blade", fieldName: "Goblin_Club", name: "Goblin Club" }],
  [44, { type: "blade", fieldName: "Spiked_Club", name: "Spiked Club" }],
  [45, { type: "blade", fieldName: "Ball_Mace", name: "Ball Mace" }],
  [46, { type: "blade", fieldName: "Spike_Mace", name: "Spike Mace" }],
  [47, { type: "blade", fieldName: "Morning_Star", name: "Morning Star" }],
  [48, { type: "blade", fieldName: "War_Hammer", name: "War Hammer" }],
  [49, { type: "blade", fieldName: "Bec_de_Corbin", name: "Bec de Corbin" }],
  [50, { type: "blade", fieldName: "War_Maul", name: "War Maul" }],
  [51, { type: "blade", fieldName: "Guisarme", name: "Guisarme" }],
  [52, { type: "blade", fieldName: "Large_Crescent", name: "Large Crescent" }],
  [53, { type: "blade", fieldName: "Sabre_Halberd", name: "Sabre Halberd" }],
  [54, { type: "blade", fieldName: "Balbriggan", name: "Balbriggan" }],
  [55, { type: "blade", fieldName: "Double_Blade", name: "Double Blade" }],
  [56, { type: "blade", fieldName: "Halberd", name: "Halberd" }],
  [57, { type: "blade", fieldName: "Wizard_Staff", name: "Wizard Staff" }],
  [58, { type: "blade", fieldName: "Clergy_Rod", name: "Clergy Rod" }],
  [59, { type: "blade", fieldName: "Summoner_Baton", name: "Summoner Baton" }],
  [60, { type: "blade", fieldName: "Shamanic_Staff", name: "Shamanic Staff" }],
  [61, { type: "blade", fieldName: "Bishops_Crosier", name: "Bishop's Crosier" }],
  [62, { type: "blade", fieldName: "Sages_Cane", name: "Sage's Cane" }],
  [63, { type: "blade", fieldName: "Langdebeve", name: "Langdebeve" }],
  [64, { type: "blade", fieldName: "Sabre_Mace", name: "Sabre Mace" }],
  [65, { type: "blade", fieldName: "Spike_Maul", name: "Spike Maul" }],
  [66, { type: "blade", fieldName: "Gloomwing", name: "Gloomwing" }],
  [67, { type: "blade", fieldName: "Mjolnir", name: "Mjolnir" }],
  [68, { type: "blade", fieldName: "Griever", name: "Griever" }],
  [69, { type: "blade", fieldName: "Destroyer", name: "Destroyer" }],
  [70, { type: "blade", fieldName: "Hand_Of_Light", name: "Hand of Light" }],
  [71, { type: "blade", fieldName: "Spear", name: "Spear" }],
  [72, { type: "blade", fieldName: "Glaive", name: "Glaive" }],
  [73, { type: "blade", fieldName: "Scorpion", name: "Scorpion" }],
  [74, { type: "blade", fieldName: "Corcesca", name: "Corcesca" }],
  [75, { type: "blade", fieldName: "Trident", name: "Trident" }],
  [76, { type: "blade", fieldName: "Awl_Pike", name: "Awl Pike" }],
  [77, { type: "blade", fieldName: "Boar_Spear", name: "Boar Spear" }],
  [78, { type: "blade", fieldName: "Fauchard", name: "Fauchard" }],
  [79, { type: "blade", fieldName: "Voulge", name: "Voulge" }],
  [80, { type: "blade", fieldName: "Pole_Axe", name: "Pole Axe" }],
  [81, { type: "blade", fieldName: "Bardysh", name: "Bardysh" }],
  [82, { type: "blade", fieldName: "Brandestoc", name: "Brandestoc" }],
  [83, { type: "blade", fieldName: "Gastraph_Bow", name: "Gastraph Bow" }],
  [84, { type: "blade", fieldName: "Light_Crossbow", name: "Light Crossbow" }],
  [85, { type: "blade", fieldName: "Target_Bow", name: "Target Bow" }],
  [86, { type: "blade", fieldName: "Windlass", name: "Windlass" }],
  [87, { type: "blade", fieldName: "Cranequin", name: "Cranequin" }],
  [88, { type: "blade", fieldName: "Lug_Crossbow", name: "Lug Crossbow" }],
  [89, { type: "blade", fieldName: "Siege_Bow", name: "Siege Bow" }],
  [90, { type: "blade", fieldName: "Arbalest", name: "Arbalest" }],

  // ── Grips: ITEMNAME 96–126 ────────────────────────────────────────
  [96, { type: "grip", fieldName: "Short_Hilt", name: "Short Hilt" }],
  [97, { type: "grip", fieldName: "Swept_Hilt", name: "Swept Hilt" }],
  [98, { type: "grip", fieldName: "Cross_Guard", name: "Cross Guard" }],
  [99, { type: "grip", fieldName: "Knuckle_Guard", name: "Knuckle Guard" }],
  [100, { type: "grip", fieldName: "Counter_Guard", name: "Counter Guard" }],
  [101, { type: "grip", fieldName: "Side_Ring", name: "Side Ring" }],
  [102, { type: "grip", fieldName: "Power_Palm", name: "Power Palm" }],
  [103, { type: "grip", fieldName: "Murderers_Hilt", name: "Murderer's Hilt" }],
  [104, { type: "grip", fieldName: "Spiral_Hilt", name: "Spiral Hilt" }],
  [105, { type: "grip", fieldName: "Wooden_Grip", name: "Wooden Grip" }],
  [106, { type: "grip", fieldName: "Sand_Face", name: "Sand Face" }],
  [107, { type: "grip", fieldName: "Czekan_Type", name: "Czekan Type" }],
  [108, { type: "grip", fieldName: "Sarissa_Grip", name: "Sarissa Grip" }],
  [109, { type: "grip", fieldName: "Heavy_Grip", name: "Heavy Grip" }],
  [110, { type: "grip", fieldName: "Gendarme", name: "Gendarme" }],
  [111, { type: "grip", fieldName: "Runkastyle", name: "Runkastyle" }],
  [112, { type: "grip", fieldName: "Grimoire_Grip", name: "Grimoire Grip" }],
  [113, { type: "grip", fieldName: "Bhuj_Type", name: "Bhuj Type" }],
  [114, { type: "grip", fieldName: "Elephant", name: "Elephant" }],
  [115, { type: "grip", fieldName: "Wooden_Pole", name: "Wooden Pole" }],
  [116, { type: "grip", fieldName: "Winged_Pole", name: "Winged Pole" }],
  [117, { type: "grip", fieldName: "Spiculum_Pole", name: "Spiculum Pole" }],
  [118, { type: "grip", fieldName: "Ahlspies", name: "Ahlspies" }],
  [119, { type: "grip", fieldName: "Framea_Pole", name: "Framea Pole" }],
  [120, { type: "grip", fieldName: "Spiral_Pole", name: "Spiral Pole" }],
  [121, { type: "grip", fieldName: "Simple_Bolt", name: "Simple Bolt" }],
  [122, { type: "grip", fieldName: "Steel_Bolt", name: "Steel Bolt" }],
  [123, { type: "grip", fieldName: "Javelin_Bolt", name: "Javelin Bolt" }],
  [124, { type: "grip", fieldName: "Falarica_Bolt", name: "Falarica Bolt" }],
  [125, { type: "grip", fieldName: "Stone_Bullet", name: "Stone Bullet" }],
  [126, { type: "grip", fieldName: "Sonic_Bullet", name: "Sonic Bullet" }],

  // ── Shields: ITEMNAME 127–142 ─────────────────────────────────────
  [127, { type: "armor", fieldName: "Buckler", name: "Buckler" }],
  [128, { type: "armor", fieldName: "Pelta", name: "Pelta" }],
  [129, { type: "armor", fieldName: "Targe", name: "Targe" }],
  [130, { type: "armor", fieldName: "Quad", name: "Quad" }],
  [131, { type: "armor", fieldName: "Circle", name: "Circle" }],
  [132, { type: "armor", fieldName: "Tower", name: "Tower" }],
  [133, { type: "armor", fieldName: "Spiked", name: "Spiked Shield" }],
  [134, { type: "armor", fieldName: "Round", name: "Round" }],
  [135, { type: "armor", fieldName: "Kite", name: "Kite" }],
  [136, { type: "armor", fieldName: "Casserole", name: "Casserole" }],
  [137, { type: "armor", fieldName: "Heater", name: "Heater" }],
  [138, { type: "armor", fieldName: "Oval", name: "Oval" }],
  [139, { type: "armor", fieldName: "Knight", name: "Knight Shield" }],
  [140, { type: "armor", fieldName: "Hoplite", name: "Hoplite Shield" }],
  [141, { type: "armor", fieldName: "Jazeraint", name: "Jazeraint" }],
  [142, { type: "armor", fieldName: "Dread", name: "Dread Shield" }],

  // ── Helms: ITEMNAME 143–158 ───────────────────────────────────────
  [143, { type: "armor", fieldName: "Bandana", name: "Bandana" }],
  [144, { type: "armor", fieldName: "Bear_Mask", name: "Bear Mask" }],
  [145, { type: "armor", fieldName: "Wizard_Hat", name: "Wizard Hat" }],
  [146, { type: "armor", fieldName: "Bone_Helm", name: "Bone Helm" }],
  [147, { type: "armor", fieldName: "Chain_Coif", name: "Chain Coif" }],
  [148, { type: "armor", fieldName: "Spangenhelm", name: "Spangenhelm" }],
  [149, { type: "armor", fieldName: "Cabasset", name: "Cabasset" }],
  [150, { type: "armor", fieldName: "Sallet", name: "Sallet" }],
  [151, { type: "armor", fieldName: "Barbut", name: "Barbut" }],
  [152, { type: "armor", fieldName: "Basinet", name: "Basinet" }],
  [153, { type: "armor", fieldName: "Armet", name: "Armet" }],
  [154, { type: "armor", fieldName: "Close_Helm", name: "Close Helm" }],
  [155, { type: "armor", fieldName: "Burgonet", name: "Burgonet" }],
  [156, { type: "armor", fieldName: "Hoplite_Helm", name: "Hoplite Helm" }],
  [157, { type: "armor", fieldName: "Jazeraint_Helm", name: "Jazeraint Helm" }],
  [158, { type: "armor", fieldName: "Dread_Helm", name: "Dread Helm" }],

  // ── Body Armor: ITEMNAME 159–174 ──────────────────────────────────
  [159, { type: "armor", fieldName: "Jerkin", name: "Jerkin" }],
  [160, { type: "armor", fieldName: "Hauberk", name: "Hauberk" }],
  [161, { type: "armor", fieldName: "Wizard_Robe", name: "Wizard Robe" }],
  [162, { type: "armor", fieldName: "Cuirass", name: "Cuirass" }],
  [163, { type: "armor", fieldName: "Banded_Mail", name: "Banded Mail" }],
  [164, { type: "armor", fieldName: "Ring_Mail", name: "Ring Mail" }],
  [165, { type: "armor", fieldName: "Chain_Mail", name: "Chain Mail" }],
  [166, { type: "armor", fieldName: "Breastplate", name: "Breastplate" }],
  [167, { type: "armor", fieldName: "Segmentata", name: "Segmentata" }],
  [168, { type: "armor", fieldName: "Scale_Armor", name: "Scale Armor" }],
  [169, { type: "armor", fieldName: "Brigandine", name: "Brigandine" }],
  [170, { type: "armor", fieldName: "Plate_Mail", name: "Plate Mail" }],
  [171, { type: "armor", fieldName: "Fluted_Armor", name: "Fluted Armor" }],
  [172, { type: "armor", fieldName: "Hoplite_Armor", name: "Hoplite Armor" }],
  [173, { type: "armor", fieldName: "Jazeraint_Armor", name: "Jazeraint Armor" }],
  [174, { type: "armor", fieldName: "Dread_Armor", name: "Dread Armor" }],

  // ── Leg Armor: ITEMNAME 175–190 ───────────────────────────────────
  [175, { type: "armor", fieldName: "Cuisse", name: "Cuisse" }],
  [176, { type: "armor", fieldName: "Sandals", name: "Sandals" }],
  [177, { type: "armor", fieldName: "Boots", name: "Boots" }],
  [178, { type: "armor", fieldName: "Long_Boots", name: "Long Boots" }],
  [179, { type: "armor", fieldName: "Light_Greave", name: "Light Greave" }],
  [180, { type: "armor", fieldName: "Ring_Leggings", name: "Ring Leggings" }],
  [181, { type: "armor", fieldName: "Chain_Leggings", name: "Chain Leggings" }],
  [182, { type: "armor", fieldName: "Fusskampf", name: "Fusskampf" }],
  [183, { type: "armor", fieldName: "Poleyn", name: "Poleyn" }],
  [184, { type: "armor", fieldName: "Jambeau", name: "Jambeau" }],
  [185, { type: "armor", fieldName: "Missaglia", name: "Missaglia" }],
  [186, { type: "armor", fieldName: "Plate_Leggings", name: "Plate Leggings" }],
  [187, { type: "armor", fieldName: "Fluted_Leggings", name: "Fluted Leggings" }],
  [188, { type: "armor", fieldName: "Hoplite_Leggings", name: "Hoplite Leggings" }],
  [189, { type: "armor", fieldName: "Jazeraint_Leggings", name: "Jazeraint Leggings" }],
  [190, { type: "armor", fieldName: "Dread_Leggings", name: "Dread Leggings" }],

  // ── Arm Armor: ITEMNAME 191–206 ───────────────────────────────────
  [191, { type: "armor", fieldName: "Bandage", name: "Bandage" }],
  [192, { type: "armor", fieldName: "Leather_Glove", name: "Leather Glove" }],
  [193, { type: "armor", fieldName: "Reinforced_Glove", name: "Reinforced Glove" }],
  [194, { type: "armor", fieldName: "Knuckles", name: "Knuckles" }],
  [195, { type: "armor", fieldName: "Ring_Sleeve", name: "Ring Sleeve" }],
  [196, { type: "armor", fieldName: "Chain_Sleeve", name: "Chain Sleeve" }],
  [197, { type: "armor", fieldName: "Gauntlet", name: "Gauntlet" }],
  [198, { type: "armor", fieldName: "Vambrace", name: "Vambrace" }],
  [199, { type: "armor", fieldName: "Plate_Glove", name: "Plate Glove" }],
  [200, { type: "armor", fieldName: "Rondanche", name: "Rondanche" }],
  [201, { type: "armor", fieldName: "Tilt_Glove", name: "Tilt Glove" }],
  [202, { type: "armor", fieldName: "Freiturnier", name: "Freiturnier" }],
  [203, { type: "armor", fieldName: "Fluted_Glove", name: "Fluted Glove" }],
  [204, { type: "armor", fieldName: "Hoplite_Glove", name: "Hoplite Glove" }],
  [205, { type: "armor", fieldName: "Jazeraint_Glove", name: "Jazeraint Glove" }],
  [206, { type: "armor", fieldName: "Dread_Glove", name: "Dread Glove" }],

  // ── Accessories: ITEMNAME 223–253 ─────────────────────────────────
  [223, { type: "armor", fieldName: "Rood_Necklace", name: "Rood Necklace" }],
  [224, { type: "armor", fieldName: "Rune_Earrings", name: "Rune Earrings" }],
  [225, { type: "armor", fieldName: "Lionhead", name: "Lionhead" }],
  [226, { type: "armor", fieldName: "Rusted_Nails", name: "Rusted Nails" }],
  [227, { type: "armor", fieldName: "Sylphid_Ring", name: "Sylphid Ring" }],
  [228, { type: "armor", fieldName: "Marduk", name: "Marduk" }],
  [229, { type: "armor", fieldName: "Salamander_Ring", name: "Salamander Ring" }],
  [230, { type: "armor", fieldName: "Tamulis_Tongue", name: "Tamulis Tongue" }],
  [231, { type: "armor", fieldName: "Gnome_Bracelet", name: "Gnome Bracelet" }],
  [232, { type: "armor", fieldName: "Palolos_Ring", name: "Palolo's Ring" }],
  [233, { type: "armor", fieldName: "Undine_Bracelet", name: "Undine Bracelet" }],
  [234, { type: "armor", fieldName: "Talian_Ring", name: "Talian Ring" }],
  [235, { type: "armor", fieldName: "Agriass_Balm", name: "Agrias's Balm" }],
  [236, { type: "armor", fieldName: "Kadesh_Ring", name: "Kadesh Ring" }],
  [237, { type: "armor", fieldName: "Agrippas_Choker", name: "Agrippa's Choker" }],
  [238, { type: "armor", fieldName: "Diadras_Earring", name: "Diadora's Earring" }],
  [239, { type: "armor", fieldName: "Titans_Ring", name: "Titan's Ring" }],
  [240, { type: "armor", fieldName: "Lau_Feis_Armlet", name: "Lau Fei's Armlet" }],
  [241, { type: "armor", fieldName: "Swan_Song", name: "Swan Song" }],
  [242, { type: "armor", fieldName: "Pushpaka", name: "Pushpaka" }],
  [243, { type: "armor", fieldName: "Edgars_Ring", name: "Edgar's Ring" }],
  [244, { type: "armor", fieldName: "Cross_Choker", name: "Cross Choker" }],
  [245, { type: "armor", fieldName: "Ghost_Hound", name: "Ghost Hound" }],
  [246, { type: "armor", fieldName: "Beaded_Amulet", name: "Beaded Amulet" }],
  [247, { type: "armor", fieldName: "Dragonhead", name: "Dragonhead" }],
  [248, { type: "armor", fieldName: "Faufnirs_Tear", name: "Faufnir's Tear" }],
  [249, { type: "armor", fieldName: "Agaless_Chain", name: "Agales's Chain" }],
  [250, { type: "armor", fieldName: "Balams_Ring", name: "Balam's Ring" }],
  [251, { type: "armor", fieldName: "Ninja_Coif", name: "Ninja Coif" }],
  [252, { type: "armor", fieldName: "Morgans_Nails", name: "Morgan's Nails" }],
  [253, { type: "armor", fieldName: "Marlenes_Ring", name: "Marlene's Ring" }],

  // ── Gems: ITEMNAME 261–306 ────────────────────────────────────────
  [261, { type: "gem", fieldName: "Talos_Feldspear", name: "Talos Feldspar" }],
  [262, { type: "gem", fieldName: "Titan_Malachite", name: "Titan Malachite" }],
  [263, { type: "gem", fieldName: "Sylphid_Topaz", name: "Sylphid Topaz" }],
  [264, { type: "gem", fieldName: "Djinn_Amber", name: "Djinn Amber" }],
  [265, { type: "gem", fieldName: "Salamander_Ruby", name: "Salamander Ruby" }],
  [266, { type: "gem", fieldName: "Ifrit_Carnelian", name: "Ifrit Carnelian" }],
  [267, { type: "gem", fieldName: "Gnome_Emerald", name: "Gnome Emerald" }],
  [268, { type: "gem", fieldName: "Dao_Moonstone", name: "Dao Moonstone" }],
  [269, { type: "gem", fieldName: "Undine_Jasper", name: "Undine Jasper" }],
  [270, { type: "gem", fieldName: "Marid_Aquamarine", name: "Marid Aquamarine" }],
  [271, { type: "gem", fieldName: "Angel_Pearl", name: "Angel Pearl" }],
  [272, { type: "gem", fieldName: "Seraphim_Diamond", name: "Seraphim Diamond" }],
  [273, { type: "gem", fieldName: "Morlock_Jet", name: "Morlock Jet" }],
  [274, { type: "gem", fieldName: "Berial_Black_Pearl", name: "Berial Black Pearl" }],
  [275, { type: "gem", fieldName: "Haeralis", name: "Haeralis" }],
  [276, { type: "gem", fieldName: "Orlandu", name: "Orlandu" }],
  [277, { type: "gem", fieldName: "Orion", name: "Orion" }],
  [278, { type: "gem", fieldName: "Ogmius", name: "Ogmius" }],
  [279, { type: "gem", fieldName: "Iocus", name: "Iocus" }],
  [280, { type: "gem", fieldName: "Balvus", name: "Balvus" }],
  [281, { type: "gem", fieldName: "Trinity", name: "Trinity" }],
  [282, { type: "gem", fieldName: "Beowulf", name: "Beowulf" }],
  [283, { type: "gem", fieldName: "Dragonite", name: "Dragonite" }],
  [284, { type: "gem", fieldName: "Sigguld", name: "Sigguld" }],
  [285, { type: "gem", fieldName: "Demonia", name: "Demonia" }],
  [286, { type: "gem", fieldName: "Altema", name: "Altema" }],
  [287, { type: "gem", fieldName: "Polaris", name: "Polaris" }],
  [288, { type: "gem", fieldName: "Basivalin", name: "Basivalin" }],
  [289, { type: "gem", fieldName: "Galerian", name: "Galerian" }],
  [290, { type: "gem", fieldName: "Vedivier", name: "Vedivier" }],
  [291, { type: "gem", fieldName: "Berion", name: "Berion" }],
  [292, { type: "gem", fieldName: "Gervin", name: "Gervin" }],
  [293, { type: "gem", fieldName: "Tertia", name: "Tertia" }],
  [294, { type: "gem", fieldName: "Lancer", name: "Lancer" }],
  [295, { type: "gem", fieldName: "Arturos", name: "Arturos" }],
  [296, { type: "gem", fieldName: "Braveheart", name: "Braveheart" }],
  [297, { type: "gem", fieldName: "Hellraiser", name: "Hellraiser" }],
  [298, { type: "gem", fieldName: "Nightkiller", name: "Nightkiller" }],
  [299, { type: "gem", fieldName: "Manabreaker", name: "Manabreaker" }],
  [300, { type: "gem", fieldName: "Powerfist", name: "Powerfist" }],
  [301, { type: "gem", fieldName: "Brainshield", name: "Brainshield" }],
  [302, { type: "gem", fieldName: "Speedster", name: "Speedster" }],
  [303, { type: "gem", fieldName: "Silent_Queen", name: "Silent Queen" }],
  [304, { type: "gem", fieldName: "Dark_Queen", name: "Dark Queen" }],
  [305, { type: "gem", fieldName: "Death_Queen", name: "Death Queen" }],
  [306, { type: "gem", fieldName: "White_Queen", name: "White Queen" }],

  // ── Consumables: ITEMNAME 323–360 ─────────────────────────────────
  [323, { type: "consumable", fieldName: "Cure_Root", name: "Cure Root" }],
  [324, { type: "consumable", fieldName: "Cure_Bulb", name: "Cure Bulb" }],
  [325, { type: "consumable", fieldName: "Cure_Tonic", name: "Cure Tonic" }],
  [326, { type: "consumable", fieldName: "Elixir_of_Queens", name: "Elixir of Queens" }],
  [327, { type: "consumable", fieldName: "Mana_Root", name: "Mana Root" }],
  [328, { type: "consumable", fieldName: "Mana_Bulb", name: "Mana Bulb" }],
  [329, { type: "consumable", fieldName: "Mana_Tonic", name: "Mana Tonic" }],
  [330, { type: "consumable", fieldName: "Elixir_of_Kings", name: "Elixir of Kings" }],
  [331, { type: "consumable", fieldName: "Vera_Root", name: "Vera Root" }],
  [332, { type: "consumable", fieldName: "Vera_Bulb", name: "Vera Bulb" }],
  [333, { type: "consumable", fieldName: "Vera_Tonic", name: "Vera Tonic" }],
  [334, { type: "consumable", fieldName: "Elixir_of_Sages", name: "Elixir of Sages" }],
  [335, { type: "consumable", fieldName: "Faerie_Wing", name: "Faerie Wing" }],
  [336, { type: "consumable", fieldName: "Angelic_Paean", name: "Angelic Paean" }],
  [337, { type: "consumable", fieldName: "Snowfly_Draught", name: "Snowfly Draught" }],
  [338, { type: "consumable", fieldName: "Alchemists_Reagent", name: "Alchemist's Reagent" }],
  [339, { type: "consumable", fieldName: "Yggdrasils_Tears", name: "Yggdrasil's Tears" }],
  [340, { type: "consumable", fieldName: "Panacea", name: "Panacea" }],
  [341, { type: "consumable", fieldName: "Sorcerers_Reagent", name: "Sorcerer's Reagent" }],
  [342, { type: "consumable", fieldName: "Eye_of_Argon", name: "Eye of Argon" }],
  [343, { type: "consumable", fieldName: "Gold_Key", name: "Gold Key" }],
  [344, { type: "consumable", fieldName: "Silver_Key", name: "Silver Key" }],
  [345, { type: "consumable", fieldName: "Bronze_Key", name: "Bronze Key" }],
  [346, { type: "consumable", fieldName: "Iron_Key", name: "Iron Key" }],
  [347, { type: "consumable", fieldName: "Cure_Potion", name: "Cure Potion" }],
  [348, { type: "consumable", fieldName: "Mana_Potion", name: "Mana Potion" }],
  [349, { type: "consumable", fieldName: "Vera_Potion", name: "Vera Potion" }],
  [350, { type: "consumable", fieldName: "Acolytes_Nostrum", name: "Acolyte's Nostrum" }],
  [351, { type: "consumable", fieldName: "Saints_Nostrum", name: "Saint's Nostrum" }],
  [352, { type: "consumable", fieldName: "Faerie_Chortle", name: "Faerie Chortle" }],
  [353, { type: "consumable", fieldName: "Spirit_Orison", name: "Spirit Orison" }],
  [354, { type: "consumable", fieldName: "Elixir_of_Mages", name: "Elixir of Mages" }],
  [355, { type: "consumable", fieldName: "Elixir_of_Dragoons", name: "Elixir of Dragoons" }],
  [356, { type: "consumable", fieldName: "Audentia", name: "Audentia" }],
  [357, { type: "consumable", fieldName: "Virtus", name: "Virtus Wine" }],
  [358, { type: "consumable", fieldName: "Valens", name: "Valens Wine" }],
  [359, { type: "consumable", fieldName: "Prudens", name: "Prudens Wine" }],
  [360, { type: "consumable", fieldName: "Volare", name: "Volare Wine" }],
])
