/**
 * Static room name lookup from zone + room IDs.
 * Source: https://datacrystal.tcrf.net/wiki/Vagrant_Story/rooms_list
 *
 * Key format: "zone,room" → room name
 */

const ROOM_MAP = new Map<string, string>([
  // Wine Cellar (Zone 9)
  ["9,1", "Entrance to Darkness"],
  ["9,2", "Room of Cheap Red Wine"],
  ["9,3", "Room of Cheap White Wine"],
  ["9,4", "Hall of Struggle"],
  ["9,5", "Smokebarrel Stair"],
  ["9,6", "Wine Guild Hall"],
  ["9,7", "Wine Magnate's Chambers"],
  ["9,8", "Fine Vintage Vault"],
  ["9,9", "Chamber of Fear"],
  ["9,10", "The Reckoning Room"],
  ["9,11", "A Laborer's Thirst"],
  ["9,12", "The Rich Drown in Wine"],
  ["9,13", "Room of Rotten Grapes"],
  ["9,16", "The Greedy One's Den"],
  ["9,17", "Worker's Breakroom"],
  ["9,18", "Blackmarket of Wines"],
  ["11,1", "The Hero's Winehall"],
  ["12,1", "The Gallows"],
  // Catacombs (Zone 13-14)
  ["13,1", "Hall of Sworn Revenge"],
  ["13,2", "The Last Blessing"],
  ["13,3", "The Weeping Corridor"],
  ["13,4", "Persecution Hall"],
  ["13,5", "The Lamenting Mother"],
  ["13,6", "Rodent-Ridden Chamber"],
  ["13,7", "Shrine to the Martyrs"],
  ["13,9", "Hall of Dying Hope"],
  ["13,10", "Bandits' Hideout"],
  ["13,11", "The Bloody Hallway"],
  ["13,12", "Faith Overcame Fear"],
  ["13,13", "The Withered Spring"],
  ["13,14", "Repent, O ye Sinners"],
  ["13,15", "The Reaper's Victims"],
  ["13,16", "The Last Stab of Hope"],
  ["13,17", "Hallway of Heroes"],
  ["14,1", "The Beast's Domain"],
  ["42,1", 'Workshop "Work of Art"'],
  // Sanctum (Zone 15-17)
  ["15,1", "Prisoners' Niche"],
  ["15,2", "Corridor of the Clerics"],
  ["15,3", "Priests' Confinement"],
  ["15,4", "Alchemists' Laboratory"],
  ["15,5", "Theology Classroom"],
  ["15,6", "Shrine of the Martyrs"],
  ["15,7", "Advent Ground"],
  ["15,8", "Passage of the Refugees"],
  ["15,11", "Stairway to the Light"],
  ["15,12", "Hallowed Hope"],
  ["15,13", "The Academia Corridor"],
  ["16,1", "Hall of Sacrilege"],
  ["17,1", "The Cleansing Chantry"],
  // Great Cathedral (Zone 22-25)
  ["22,1", "Sanity and Madness"],
  ["22,5", "Truth and Lies"],
  ["22,7", "Order and Chaos"],
  ["22,8", "The Victor's Laurels"],
  ["22,9", "Struggle for the Soul"],
  ["22,10", "An Offering of Souls"],
  ["23,2", "He Screams for Mercy"],
  ["23,3", "Light and Dark Wage War"],
  ["23,4", "Abasement from Above"],
  ["23,5", "The Heretics' Story"],
  ["23,6", "The Wine-Lecher's Fall"],
  ["24,1", "The Flayed Confessional"],
  ["24,2", "Monk's Leap"],
  ["24,3", "Where Darkness Spreads"],
  ["24,4", "Hieratic Recollections"],
  ["24,5", "A Light in the Dark"],
  ["24,6", "The Poisoned Chapel"],
  ["24,7", "Sin and Punishment"],
  ["24,8", "Cracked Pleasures"],
  ["24,9", "Into Holy Battle"],
  ["24,10", "Maelstrom of Malice"],
  ["24,11", "The Acolyte's Weakness"],
  ["24,12", "The Hall of Broken Vows"],
  ["24,13", "The Melodics of Madness"],
  ["24,14", "Free from Base Desires"],
  ["24,15", "The Convent Room"],
  ["24,16", "Hopes of the Idealist"],
  ["25,1", "An Arrow into Darkness"],
  ["25,2", "What Ails You, Kills You"],
  ["25,3", "Where the Soul Rots"],
  ["25,4", "Despair of the Fallen"],
  ["25,5", "The Atrium"],
  // Abandoned Mines B1 (Zone 50)
  ["50,1", "Dreamers' Entrance"],
  ["50,2", "Miners' Resting Hall"],
  ["50,3", "The Crossing"],
  ["50,4", "Conflict and Accord"],
  ["50,5", "The Suicide King"],
  ["50,6", "The End of the Line"],
  ["50,7", "The Battle's Beginning"],
  ["50,8", "What Lies Ahead?"],
  ["50,9", "The Fruits of Friendship"],
  ["50,10", "The Earthquake's Mark"],
  ["50,11", "Coal Mine Storage"],
  ["50,12", "The Passion of Lovers"],
  ["50,13", "The Hall of Hope"],
  ["50,14", "The Dark Tunnel"],
  ["50,15", "Rust in Peace"],
  ["50,16", "Everwant Passage"],
  ["50,17", "Mining Regrets"],
  ["50,18", "The Smeltry"],
  ["50,19", "Clash of Hyaenas"],
  ["50,20", "Greed Knows No Bounds"],
  ["50,21", "Live Long and Prosper"],
  ["50,22", "Pray to the Mineral Gods"],
  ["50,23", "Traitor's Parting"],
  ["50,24", "Escapeway"],
  // Abandoned Mines B2 (Zone 51)
  ["51,1", "Gambler's Passage"],
  ["51,2", "Treaty Room"],
  ["51,3", "The Miner's End"],
  ["51,4", "Work, Then Die"],
  ["51,5", "Bandits' Hollow"],
  ["51,6", "Delusions of Happiness"],
  ["51,7", "Dining in Darkness"],
  ["51,8", "Subtellurian Horrors"],
  ["51,9", "Hidden Resources"],
  ["51,10", "Way of Lost Children"],
  ["51,11", "Hall of the Empty Sconce"],
  ["51,12", "Acolyte's Burial Vault"],
  ["51,13", "Hall of Contemplation"],
  ["51,14", "The Abandoned Catspaw"],
  ["51,15", "Tomb of the Reborn"],
  ["51,16", "The Fallen Bricklayer"],
  ["51,17", "Crossing of Blood"],
  ["51,18", "Fool's Gold, Fool's Loss"],
  ["51,19", "Cry of the Beast"],
  ["51,20", "Senses Lost"],
  ["51,21", "Desire's Passage"],
  ["51,22", "Kilroy Was Here"],
  ["51,23", "Suicidal Desires"],
  ["51,24", "The Ore of Legend"],
  ["51,25", "Lambs to the Slaughter"],
  ["51,26", "A Wager of Noble Gold"],
  ["51,27", "The Lunatic Veins"],
  ["51,28", "Corridor of Shade"],
  ["51,29", "Revelation Shaft"],
  // Limestone Quarry (Zone 53)
  ["53,1", "Dark Abhors Light"],
  ["53,2", "Dream of the Holy Land"],
  ["53,3", "The Ore Road"],
  ["53,4", "Atone for Eternity"],
  ["53,5", "The Air Stirs"],
  ["53,6", "Bonds of Friendship"],
  ["53,7", "Stair to Sanctuary"],
  ["53,8", "The Fallen Hall"],
  ["53,9", "The Rotten Core"],
  ["53,10", "Bacchus is Cheap"],
  ["53,11", "Screams of the Wounded"],
  ["53,12", "The Ore-Bearers"],
  ["53,13", "The Dreamer's Climb"],
  ["53,14", "Sinner's Sustenence"],
  ["53,15", "The Timely Dew of Sleep"],
  ["53,16", "Companions in Arms"],
  ["53,17", "The Auction Block"],
  ["53,18", "Ascension"],
  ["53,19", "Where the Serpent Hunts"],
  ["53,20", "Ants Prepare for Winter"],
  ["53,21", "Drowned in Fleeting Joy"],
  ["53,22", "The Laborer's Bonfire"],
  ["53,23", "Stone and Sulfurous Fire"],
  ["53,24", "Torture Without End"],
  ["53,25", "Way Down"],
  ["53,26", "Excavated Hollow"],
  ["53,27", "Parting Regrets"],
  ["53,28", "Corridor of Tales"],
  ["53,29", "Dust Shall Eat the Days"],
  ["53,30", "Hall of the Wage-Paying"],
  ["53,32", "Tunnel of the Heartless"],
  // Temple of Kiltia (Zone 54)
  ["54,1", "Stair to the Sinners"],
  ["54,2", "Slaughter of the Innocent"],
  ["54,3", "The Fallen Knight"],
  ["54,4", "The Oracle Sins No More"],
  ["54,5", "Awaiting Retribution"],
  // Forgotten Pathway (Zone 52)
  ["52,1", "Shelter From the Quake"],
  ["52,2", "Buried Alive"],
  ["52,3", "Movement of Fear"],
  ["52,4", "Facing Your Illusions"],
  ["52,5", "The Darkness Drinks"],
  ["52,6", "Fear and Loathing"],
  ["52,7", "Blood and the Beast"],
  ["52,8", "Where Body and Soul Part"],
  // Iron Maiden B1 (Zone 55)
  ["55,1", "The Cage"],
  ["55,2", "The Cauldron"],
  ["55,3", "Wooden Horse"],
  ["55,4", "Starvation"],
  ["55,5", "The Breast Ripper"],
  ["55,6", "The Pear"],
  ["55,7", "The Whirligig"],
  ["55,8", "Spanish Tickler"],
  ["55,9", "Heretic's Fork"],
  ["55,10", "The Chair of Spikes"],
  ["55,11", "Blooding"],
  ["55,12", "Bootikens"],
  ["55,13", "Burial"],
  ["55,14", "Burning"],
  ["55,15", "Cleansing the Soul"],
  ["55,16", "The Garotte"],
  ["55,17", "Hanging"],
  ["55,18", "Impalement"],
  ["55,19", "Knotting"],
  ["55,20", "The Branks"],
  ["55,21", "The Wheel"],
  ["55,22", "The Judas Cradle"],
  ["55,23", "The Ducking Stool"],
  // Iron Maiden B2 (Zone 56)
  ["56,1", "The Eunics' Lot"],
  ["56,2", "Ordeal By Fire"],
  ["56,3", "Tablillas"],
  ["56,4", "The Oven at Neisse"],
  ["56,5", "Strangulation"],
  ["56,6", "Pressing"],
  ["56,7", "The Strappado"],
  ["56,8", "The Mind Burns"],
  ["56,9", "Thumbscrews"],
  ["56,10", "The Rack"],
  ["56,11", "The Saw"],
  ["56,12", "Ordeal By Water"],
  ["56,13", "The Cold's Bridle"],
  ["56,14", "Brank"],
  ["56,15", "The Shin-Vice"],
  ["56,16", "Squassation"],
  ["56,17", "The Spider"],
  ["56,18", "Lead Sprinkler"],
  ["56,19", "Pendulum"],
  ["56,20", "Dragging"],
  ["56,21", "Tongue Slicer"],
  ["56,22", "Tormentum Insomniae"],
  ["56,23", "The Iron Maiden"],
  ["56,24", "Saint Elmo's Belt"],
  ["56,25", "Judgement"],
  ["56,26", "Dunking the Witch"],
  // Workshops
  ["47,1", 'Workshop "Godhands"'],
  ["43,1", 'Workshop "Magic Hammer"'],
  ["44,1", 'Wkshop "Keane\'s Crafts"'],
  ["45,1", 'Workshop "Metal Works"'],
  ["46,1", 'Wkshop "Junction Point"'],
  // Undercity West (Zone 48)
  ["48,1", "The Bread Peddler's Way"],
  ["48,2", "Way of the Mother Lode"],
  ["48,3", "Sewer of Ravenous Rats"],
  ["48,4", "Underdark Fishmarket"],
  ["48,5", "The Sunless Way"],
  ["48,6", "Remembering Days of Yore"],
  ["48,7", "Where the Hunter Climbed"],
  ["48,8", "Larder for a Lean Winter"],
  ["48,9", "Hall of Poverty"],
  ["48,10", "The Washing-Woman's Way"],
  ["48,11", "Beggars of the Mouthharp"],
  ["48,12", "Corner of the Wretched"],
  ["48,13", "Path to the Greengrocer"],
  ["48,14", "Crossroads of Rest"],
  ["48,15", "Path of the Children"],
  ["48,16", "Fear of the Fall"],
  ["48,17", "Sinner's Corner"],
  ["48,18", "Nameless Dark Oblivion"],
  ["48,19", "Corner of Prayers"],
  ["48,20", "Hope Obstructed"],
  ["48,21", "The Children's Hideout"],
  ["48,22", "The Crumbling Market"],
  ["48,23", "Tears from Empty Sockets"],
  ["48,24", "Where Flood Waters Ran"],
  ["48,25", "The Body Fragile Yields"],
  ["48,26", "Salvation for the Mother"],
  ["48,27", "Bite the Master's Wounds"],
  // Undercity East (Zone 49)
  ["49,1", "Hall to a New World"],
  ["49,2", "Place of Free Words"],
  ["49,3", "Bazaar of the Bizarre"],
  ["49,4", "Noble Gold and Silk"],
  ["49,5", "A Knight Sells his Sword"],
  ["49,6", "Gemsword Blackmarket"],
  ["49,7", "The Pirate's Son"],
  ["49,8", "Sale of the Sword"],
  ["49,9", "Weapons Not Allowed"],
  ["49,10", "The Greengrocer's Stair"],
  ["49,11", "Where Black Waters Ran"],
  ["49,12", "Arms Against Invaders"],
  ["49,13", "Catspaw Blackmarket"],
  // Keep (Zone 28-29)
  ["29,1", "The Warrior's Rest"],
  ["29,3", "The Soldier's Bedding"],
  ["29,4", "A Storm of Arrows"],
  ["29,5", "Urge the Boy On"],
  ["29,6", "A Taste of the Spoils"],
  ["29,7", "Wiping Blood from Blades"],
  ["28,1", "Students of Death"],
  ["28,2", "The Gabled Hall"],
  ["28,3", "Where the Master Fell"],
  ["28,4", "The Weeping Boy"],
  ["28,5", "Swords for the Land"],
  ["28,6", "In Wait of the Foe"],
  ["28,7", "Where Weary Riders Rest"],
  ["28,8", "The Boy's Training Room"],
  ["28,9", "Train and Grow Strong"],
  ["28,10", "The Squire's Gathering"],
  ["28,11", "The Invaders are Found"],
  ["28,12", "The Dream-Weavers"],
  ["28,13", "The Cornered Savage"],
  ["28,14", "Traces of Invasion Past"],
  ["28,15", "From Squire to Knight"],
  ["28,16", "Be for Battle Prepared"],
  ["28,17", "Destruction and Rebirth"],
  ["28,18", "From Boy to Hero"],
  ["28,19", "A Welcome Invasion"],
  // Snowfly Forest (Zone 40-41)
  ["40,1", "The Hunt Begins"],
  ["40,2", "Which Way Home"],
  ["40,3", "The Giving Trees"],
  ["40,4", "The Wounded Boar"],
  ["40,5", "Golden Egg Way"],
  ["40,6", "The Birds and the Bees"],
  ["40,7", "The Woodcutter's Run"],
  ["40,8", "The Wolves' Choice"],
  ["40,9", "Howl of the Wolf King"],
  ["40,10", "Fluttering Hope"],
  ["40,11", "Traces of the Beast"],
  ["40,12", "The Yellow Wood"],
  ["40,13", "They Also Feed"],
  ["40,14", "Where Soft Rains Fell"],
  ["40,15", "The Spirit Trees"],
  ["40,16", "The Silent Hedges"],
  ["40,17", "Lamenting to the Moon"],
  ["40,18", "The Hollow Hills"],
  ["40,19", "Running with the Wolves"],
  ["40,20", "You Are the Prey"],
  ["40,21", "The Secret Path"],
  ["40,22", "The Faerie Circle"],
  ["40,23", "Return to the Land"],
  ["40,24", "Forest River"],
  ["40,25", "Hewn from Nature"],
  ["40,26", "The Wood Gate"],
  ["41,1", "Steady the Boar-Spears"],
  ["41,2", "The Boar's Revenge"],
  ["41,3", "Nature's Womb"],
  // Town Center (Zone 32, 34-39)
  ["32,1", "Rue Vermillion"],
  ["32,2", "The Rene Coastroad"],
  ["32,3", "Rue Mal Fallde"],
  ["32,4", "Tircolas Flow"],
  ["32,5", "Glacialdra Kirk Ruins"],
  ["32,6", "Rue Bouquet"],
  ["32,7", "Villeport Way"],
  ["32,8", "Rue Sant D'alsa"],
  ["32,9", "Valdiman Gates"],
  ["32,10", "Rue Faltes"],
  ["32,11", "Forcas Rise"],
  ["32,12", "Rue Aliano"],
  ["32,13", "Rue Volnac"],
  ["32,14", "Rue Morgue"],
  ["32,16", "Rue Lejour"],
  ["32,17", "Kesch Bridge"],
  ["32,18", "Rue Crimnade"],
  ["32,19", "Rue Fisserano"],
  ["32,20", "Shasras Hill Park"],
  ["34,1", "Dinas Walk"],
  ["35,1", "Zebel's Walk"],
  ["36,1", "Gharmes Walk"],
  ["37,1", "The House Khazabas"],
  ["38,1", "The House Gilgitte"],
  ["39,1", "Plateia Lumitar"],
  // Escapeway / Dark areas (Zone 30-31)
  ["30,1", "The Dark Coast"],
  ["30,2", "Hall of Prayer"],
  ["30,3", "Those who Drink the Dark"],
  ["30,4", "The Chapel of Meschaunce"],
  ["30,5", "The Resentful Ones"],
  ["30,6", "Those who Fear the Light"],
  ["31,1", "Chamber of Reason"],
  ["31,2", "Exit to City Center"],
])

/**
 * Look up a room name from zone and room IDs.
 * Returns the room name, or a fallback string if not found.
 */
export function getRoomName(zoneId: number, roomId: number): string {
  // Try exact match first, then fall back to room 0→1 or 1→0
  // (some zones store room IDs 0-based, others 1-based)
  return (
    ROOM_MAP.get(`${zoneId},${roomId}`) ??
    ROOM_MAP.get(`${zoneId},${roomId === 0 ? 1 : 0}`) ??
    ""
  )
}
