/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeaponsRouteImport } from './routes/weapons'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MaterialGridRouteImport } from './routes/material-grid'
import { Route as GripsRouteImport } from './routes/grips'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as ConsumablesRouteImport } from './routes/consumables'
import { Route as ArmorRouteImport } from './routes/armor'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CraftingIndexRouteImport } from './routes/crafting/index'

const WeaponsRoute = WeaponsRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialGridRoute = MaterialGridRouteImport.update({
  id: '/material-grid',
  path: '/material-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const GripsRoute = GripsRouteImport.update({
  id: '/grips',
  path: '/grips',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumablesRoute = ConsumablesRouteImport.update({
  id: '/consumables',
  path: '/consumables',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmorRoute = ArmorRouteImport.update({
  id: '/armor',
  path: '/armor',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingIndexRoute = CraftingIndexRouteImport.update({
  id: '/crafting/',
  path: '/crafting/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/armor': typeof ArmorRoute
  '/consumables': typeof ConsumablesRoute
  '/gems': typeof GemsRoute
  '/grips': typeof GripsRoute
  '/material-grid': typeof MaterialGridRoute
  '/materials': typeof MaterialsRoute
  '/weapons': typeof WeaponsRoute
  '/crafting/': typeof CraftingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/armor': typeof ArmorRoute
  '/consumables': typeof ConsumablesRoute
  '/gems': typeof GemsRoute
  '/grips': typeof GripsRoute
  '/material-grid': typeof MaterialGridRoute
  '/materials': typeof MaterialsRoute
  '/weapons': typeof WeaponsRoute
  '/crafting': typeof CraftingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/armor': typeof ArmorRoute
  '/consumables': typeof ConsumablesRoute
  '/gems': typeof GemsRoute
  '/grips': typeof GripsRoute
  '/material-grid': typeof MaterialGridRoute
  '/materials': typeof MaterialsRoute
  '/weapons': typeof WeaponsRoute
  '/crafting/': typeof CraftingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/armor'
    | '/consumables'
    | '/gems'
    | '/grips'
    | '/material-grid'
    | '/materials'
    | '/weapons'
    | '/crafting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/armor'
    | '/consumables'
    | '/gems'
    | '/grips'
    | '/material-grid'
    | '/materials'
    | '/weapons'
    | '/crafting'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/armor'
    | '/consumables'
    | '/gems'
    | '/grips'
    | '/material-grid'
    | '/materials'
    | '/weapons'
    | '/crafting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ArmorRoute: typeof ArmorRoute
  ConsumablesRoute: typeof ConsumablesRoute
  GemsRoute: typeof GemsRoute
  GripsRoute: typeof GripsRoute
  MaterialGridRoute: typeof MaterialGridRoute
  MaterialsRoute: typeof MaterialsRoute
  WeaponsRoute: typeof WeaponsRoute
  CraftingIndexRoute: typeof CraftingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weapons': {
      id: '/weapons'
      path: '/weapons'
      fullPath: '/weapons'
      preLoaderRoute: typeof WeaponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-grid': {
      id: '/material-grid'
      path: '/material-grid'
      fullPath: '/material-grid'
      preLoaderRoute: typeof MaterialGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grips': {
      id: '/grips'
      path: '/grips'
      fullPath: '/grips'
      preLoaderRoute: typeof GripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumables': {
      id: '/consumables'
      path: '/consumables'
      fullPath: '/consumables'
      preLoaderRoute: typeof ConsumablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armor': {
      id: '/armor'
      path: '/armor'
      fullPath: '/armor'
      preLoaderRoute: typeof ArmorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting/': {
      id: '/crafting/'
      path: '/crafting'
      fullPath: '/crafting/'
      preLoaderRoute: typeof CraftingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ArmorRoute: ArmorRoute,
  ConsumablesRoute: ConsumablesRoute,
  GemsRoute: GemsRoute,
  GripsRoute: GripsRoute,
  MaterialGridRoute: MaterialGridRoute,
  MaterialsRoute: MaterialsRoute,
  WeaponsRoute: WeaponsRoute,
  CraftingIndexRoute: CraftingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
