/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MaterialGridRouteImport } from './routes/material-grid'
import { Route as WeaponsRouteRouteImport } from './routes/weapons/route'
import { Route as SpellsRouteRouteImport } from './routes/spells/route'
import { Route as SigilsRouteRouteImport } from './routes/sigils/route'
import { Route as KeysRouteRouteImport } from './routes/keys/route'
import { Route as GripsRouteRouteImport } from './routes/grips/route'
import { Route as GemsRouteRouteImport } from './routes/gems/route'
import { Route as ConsumablesRouteRouteImport } from './routes/consumables/route'
import { Route as ArmorRouteRouteImport } from './routes/armor/route'
import { Route as AccessoriesRouteRouteImport } from './routes/accessories/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeaponsIndexRouteImport } from './routes/weapons/index'
import { Route as SpellsIndexRouteImport } from './routes/spells/index'
import { Route as SigilsIndexRouteImport } from './routes/sigils/index'
import { Route as KeysIndexRouteImport } from './routes/keys/index'
import { Route as GripsIndexRouteImport } from './routes/grips/index'
import { Route as GemsIndexRouteImport } from './routes/gems/index'
import { Route as CraftingIndexRouteImport } from './routes/crafting/index'
import { Route as ConsumablesIndexRouteImport } from './routes/consumables/index'
import { Route as ArmorIndexRouteImport } from './routes/armor/index'
import { Route as AccessoriesIndexRouteImport } from './routes/accessories/index'
import { Route as WeaponsIdRouteImport } from './routes/weapons/$id'
import { Route as SpellsIdRouteImport } from './routes/spells/$id'
import { Route as SigilsIdRouteImport } from './routes/sigils/$id'
import { Route as KeysIdRouteImport } from './routes/keys/$id'
import { Route as GripsIdRouteImport } from './routes/grips/$id'
import { Route as GemsIdRouteImport } from './routes/gems/$id'
import { Route as ConsumablesIdRouteImport } from './routes/consumables/$id'
import { Route as ArmorIdRouteImport } from './routes/armor/$id'
import { Route as AccessoriesIdRouteImport } from './routes/accessories/$id'

const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialGridRoute = MaterialGridRouteImport.update({
  id: '/material-grid',
  path: '/material-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsRouteRoute = WeaponsRouteRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => rootRouteImport,
} as any)
const SpellsRouteRoute = SpellsRouteRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => rootRouteImport,
} as any)
const SigilsRouteRoute = SigilsRouteRouteImport.update({
  id: '/sigils',
  path: '/sigils',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRouteRoute = KeysRouteRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const GripsRouteRoute = GripsRouteRouteImport.update({
  id: '/grips',
  path: '/grips',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRouteRoute = GemsRouteRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumablesRouteRoute = ConsumablesRouteRouteImport.update({
  id: '/consumables',
  path: '/consumables',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmorRouteRoute = ArmorRouteRouteImport.update({
  id: '/armor',
  path: '/armor',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRouteRoute = AccessoriesRouteRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsIndexRoute = WeaponsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeaponsRouteRoute,
} as any)
const SpellsIndexRoute = SpellsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpellsRouteRoute,
} as any)
const SigilsIndexRoute = SigilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SigilsRouteRoute,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeysRouteRoute,
} as any)
const GripsIndexRoute = GripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GripsRouteRoute,
} as any)
const GemsIndexRoute = GemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GemsRouteRoute,
} as any)
const CraftingIndexRoute = CraftingIndexRouteImport.update({
  id: '/crafting/',
  path: '/crafting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumablesIndexRoute = ConsumablesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumablesRouteRoute,
} as any)
const ArmorIndexRoute = ArmorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArmorRouteRoute,
} as any)
const AccessoriesIndexRoute = AccessoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccessoriesRouteRoute,
} as any)
const WeaponsIdRoute = WeaponsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WeaponsRouteRoute,
} as any)
const SpellsIdRoute = SpellsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpellsRouteRoute,
} as any)
const SigilsIdRoute = SigilsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SigilsRouteRoute,
} as any)
const KeysIdRoute = KeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KeysRouteRoute,
} as any)
const GripsIdRoute = GripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GripsRouteRoute,
} as any)
const GemsIdRoute = GemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GemsRouteRoute,
} as any)
const ConsumablesIdRoute = ConsumablesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConsumablesRouteRoute,
} as any)
const ArmorIdRoute = ArmorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArmorRouteRoute,
} as any)
const AccessoriesIdRoute = AccessoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccessoriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteRouteWithChildren
  '/armor': typeof ArmorRouteRouteWithChildren
  '/consumables': typeof ConsumablesRouteRouteWithChildren
  '/gems': typeof GemsRouteRouteWithChildren
  '/grips': typeof GripsRouteRouteWithChildren
  '/keys': typeof KeysRouteRouteWithChildren
  '/sigils': typeof SigilsRouteRouteWithChildren
  '/spells': typeof SpellsRouteRouteWithChildren
  '/weapons': typeof WeaponsRouteRouteWithChildren
  '/material-grid': typeof MaterialGridRoute
  '/materials': typeof MaterialsRoute
  '/accessories/$id': typeof AccessoriesIdRoute
  '/armor/$id': typeof ArmorIdRoute
  '/consumables/$id': typeof ConsumablesIdRoute
  '/gems/$id': typeof GemsIdRoute
  '/grips/$id': typeof GripsIdRoute
  '/keys/$id': typeof KeysIdRoute
  '/sigils/$id': typeof SigilsIdRoute
  '/spells/$id': typeof SpellsIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/armor/': typeof ArmorIndexRoute
  '/consumables/': typeof ConsumablesIndexRoute
  '/crafting/': typeof CraftingIndexRoute
  '/gems/': typeof GemsIndexRoute
  '/grips/': typeof GripsIndexRoute
  '/keys/': typeof KeysIndexRoute
  '/sigils/': typeof SigilsIndexRoute
  '/spells/': typeof SpellsIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/material-grid': typeof MaterialGridRoute
  '/materials': typeof MaterialsRoute
  '/accessories/$id': typeof AccessoriesIdRoute
  '/armor/$id': typeof ArmorIdRoute
  '/consumables/$id': typeof ConsumablesIdRoute
  '/gems/$id': typeof GemsIdRoute
  '/grips/$id': typeof GripsIdRoute
  '/keys/$id': typeof KeysIdRoute
  '/sigils/$id': typeof SigilsIdRoute
  '/spells/$id': typeof SpellsIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/accessories': typeof AccessoriesIndexRoute
  '/armor': typeof ArmorIndexRoute
  '/consumables': typeof ConsumablesIndexRoute
  '/crafting': typeof CraftingIndexRoute
  '/gems': typeof GemsIndexRoute
  '/grips': typeof GripsIndexRoute
  '/keys': typeof KeysIndexRoute
  '/sigils': typeof SigilsIndexRoute
  '/spells': typeof SpellsIndexRoute
  '/weapons': typeof WeaponsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteRouteWithChildren
  '/armor': typeof ArmorRouteRouteWithChildren
  '/consumables': typeof ConsumablesRouteRouteWithChildren
  '/gems': typeof GemsRouteRouteWithChildren
  '/grips': typeof GripsRouteRouteWithChildren
  '/keys': typeof KeysRouteRouteWithChildren
  '/sigils': typeof SigilsRouteRouteWithChildren
  '/spells': typeof SpellsRouteRouteWithChildren
  '/weapons': typeof WeaponsRouteRouteWithChildren
  '/material-grid': typeof MaterialGridRoute
  '/materials': typeof MaterialsRoute
  '/accessories/$id': typeof AccessoriesIdRoute
  '/armor/$id': typeof ArmorIdRoute
  '/consumables/$id': typeof ConsumablesIdRoute
  '/gems/$id': typeof GemsIdRoute
  '/grips/$id': typeof GripsIdRoute
  '/keys/$id': typeof KeysIdRoute
  '/sigils/$id': typeof SigilsIdRoute
  '/spells/$id': typeof SpellsIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/armor/': typeof ArmorIndexRoute
  '/consumables/': typeof ConsumablesIndexRoute
  '/crafting/': typeof CraftingIndexRoute
  '/gems/': typeof GemsIndexRoute
  '/grips/': typeof GripsIndexRoute
  '/keys/': typeof KeysIndexRoute
  '/sigils/': typeof SigilsIndexRoute
  '/spells/': typeof SpellsIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/armor'
    | '/consumables'
    | '/gems'
    | '/grips'
    | '/keys'
    | '/sigils'
    | '/spells'
    | '/weapons'
    | '/material-grid'
    | '/materials'
    | '/accessories/$id'
    | '/armor/$id'
    | '/consumables/$id'
    | '/gems/$id'
    | '/grips/$id'
    | '/keys/$id'
    | '/sigils/$id'
    | '/spells/$id'
    | '/weapons/$id'
    | '/accessories/'
    | '/armor/'
    | '/consumables/'
    | '/crafting/'
    | '/gems/'
    | '/grips/'
    | '/keys/'
    | '/sigils/'
    | '/spells/'
    | '/weapons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/material-grid'
    | '/materials'
    | '/accessories/$id'
    | '/armor/$id'
    | '/consumables/$id'
    | '/gems/$id'
    | '/grips/$id'
    | '/keys/$id'
    | '/sigils/$id'
    | '/spells/$id'
    | '/weapons/$id'
    | '/accessories'
    | '/armor'
    | '/consumables'
    | '/crafting'
    | '/gems'
    | '/grips'
    | '/keys'
    | '/sigils'
    | '/spells'
    | '/weapons'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/armor'
    | '/consumables'
    | '/gems'
    | '/grips'
    | '/keys'
    | '/sigils'
    | '/spells'
    | '/weapons'
    | '/material-grid'
    | '/materials'
    | '/accessories/$id'
    | '/armor/$id'
    | '/consumables/$id'
    | '/gems/$id'
    | '/grips/$id'
    | '/keys/$id'
    | '/sigils/$id'
    | '/spells/$id'
    | '/weapons/$id'
    | '/accessories/'
    | '/armor/'
    | '/consumables/'
    | '/crafting/'
    | '/gems/'
    | '/grips/'
    | '/keys/'
    | '/sigils/'
    | '/spells/'
    | '/weapons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRouteRoute: typeof AccessoriesRouteRouteWithChildren
  ArmorRouteRoute: typeof ArmorRouteRouteWithChildren
  ConsumablesRouteRoute: typeof ConsumablesRouteRouteWithChildren
  GemsRouteRoute: typeof GemsRouteRouteWithChildren
  GripsRouteRoute: typeof GripsRouteRouteWithChildren
  KeysRouteRoute: typeof KeysRouteRouteWithChildren
  SigilsRouteRoute: typeof SigilsRouteRouteWithChildren
  SpellsRouteRoute: typeof SpellsRouteRouteWithChildren
  WeaponsRouteRoute: typeof WeaponsRouteRouteWithChildren
  MaterialGridRoute: typeof MaterialGridRoute
  MaterialsRoute: typeof MaterialsRoute
  CraftingIndexRoute: typeof CraftingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-grid': {
      id: '/material-grid'
      path: '/material-grid'
      fullPath: '/material-grid'
      preLoaderRoute: typeof MaterialGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons': {
      id: '/weapons'
      path: '/weapons'
      fullPath: '/weapons'
      preLoaderRoute: typeof WeaponsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spells': {
      id: '/spells'
      path: '/spells'
      fullPath: '/spells'
      preLoaderRoute: typeof SpellsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigils': {
      id: '/sigils'
      path: '/sigils'
      fullPath: '/sigils'
      preLoaderRoute: typeof SigilsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grips': {
      id: '/grips'
      path: '/grips'
      fullPath: '/grips'
      preLoaderRoute: typeof GripsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumables': {
      id: '/consumables'
      path: '/consumables'
      fullPath: '/consumables'
      preLoaderRoute: typeof ConsumablesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armor': {
      id: '/armor'
      path: '/armor'
      fullPath: '/armor'
      preLoaderRoute: typeof ArmorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons/': {
      id: '/weapons/'
      path: '/'
      fullPath: '/weapons/'
      preLoaderRoute: typeof WeaponsIndexRouteImport
      parentRoute: typeof WeaponsRouteRoute
    }
    '/spells/': {
      id: '/spells/'
      path: '/'
      fullPath: '/spells/'
      preLoaderRoute: typeof SpellsIndexRouteImport
      parentRoute: typeof SpellsRouteRoute
    }
    '/sigils/': {
      id: '/sigils/'
      path: '/'
      fullPath: '/sigils/'
      preLoaderRoute: typeof SigilsIndexRouteImport
      parentRoute: typeof SigilsRouteRoute
    }
    '/keys/': {
      id: '/keys/'
      path: '/'
      fullPath: '/keys/'
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof KeysRouteRoute
    }
    '/grips/': {
      id: '/grips/'
      path: '/'
      fullPath: '/grips/'
      preLoaderRoute: typeof GripsIndexRouteImport
      parentRoute: typeof GripsRouteRoute
    }
    '/gems/': {
      id: '/gems/'
      path: '/'
      fullPath: '/gems/'
      preLoaderRoute: typeof GemsIndexRouteImport
      parentRoute: typeof GemsRouteRoute
    }
    '/crafting/': {
      id: '/crafting/'
      path: '/crafting'
      fullPath: '/crafting/'
      preLoaderRoute: typeof CraftingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumables/': {
      id: '/consumables/'
      path: '/'
      fullPath: '/consumables/'
      preLoaderRoute: typeof ConsumablesIndexRouteImport
      parentRoute: typeof ConsumablesRouteRoute
    }
    '/armor/': {
      id: '/armor/'
      path: '/'
      fullPath: '/armor/'
      preLoaderRoute: typeof ArmorIndexRouteImport
      parentRoute: typeof ArmorRouteRoute
    }
    '/accessories/': {
      id: '/accessories/'
      path: '/'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AccessoriesIndexRouteImport
      parentRoute: typeof AccessoriesRouteRoute
    }
    '/weapons/$id': {
      id: '/weapons/$id'
      path: '/$id'
      fullPath: '/weapons/$id'
      preLoaderRoute: typeof WeaponsIdRouteImport
      parentRoute: typeof WeaponsRouteRoute
    }
    '/spells/$id': {
      id: '/spells/$id'
      path: '/$id'
      fullPath: '/spells/$id'
      preLoaderRoute: typeof SpellsIdRouteImport
      parentRoute: typeof SpellsRouteRoute
    }
    '/sigils/$id': {
      id: '/sigils/$id'
      path: '/$id'
      fullPath: '/sigils/$id'
      preLoaderRoute: typeof SigilsIdRouteImport
      parentRoute: typeof SigilsRouteRoute
    }
    '/keys/$id': {
      id: '/keys/$id'
      path: '/$id'
      fullPath: '/keys/$id'
      preLoaderRoute: typeof KeysIdRouteImport
      parentRoute: typeof KeysRouteRoute
    }
    '/grips/$id': {
      id: '/grips/$id'
      path: '/$id'
      fullPath: '/grips/$id'
      preLoaderRoute: typeof GripsIdRouteImport
      parentRoute: typeof GripsRouteRoute
    }
    '/gems/$id': {
      id: '/gems/$id'
      path: '/$id'
      fullPath: '/gems/$id'
      preLoaderRoute: typeof GemsIdRouteImport
      parentRoute: typeof GemsRouteRoute
    }
    '/consumables/$id': {
      id: '/consumables/$id'
      path: '/$id'
      fullPath: '/consumables/$id'
      preLoaderRoute: typeof ConsumablesIdRouteImport
      parentRoute: typeof ConsumablesRouteRoute
    }
    '/armor/$id': {
      id: '/armor/$id'
      path: '/$id'
      fullPath: '/armor/$id'
      preLoaderRoute: typeof ArmorIdRouteImport
      parentRoute: typeof ArmorRouteRoute
    }
    '/accessories/$id': {
      id: '/accessories/$id'
      path: '/$id'
      fullPath: '/accessories/$id'
      preLoaderRoute: typeof AccessoriesIdRouteImport
      parentRoute: typeof AccessoriesRouteRoute
    }
  }
}

interface AccessoriesRouteRouteChildren {
  AccessoriesIdRoute: typeof AccessoriesIdRoute
  AccessoriesIndexRoute: typeof AccessoriesIndexRoute
}

const AccessoriesRouteRouteChildren: AccessoriesRouteRouteChildren = {
  AccessoriesIdRoute: AccessoriesIdRoute,
  AccessoriesIndexRoute: AccessoriesIndexRoute,
}

const AccessoriesRouteRouteWithChildren =
  AccessoriesRouteRoute._addFileChildren(AccessoriesRouteRouteChildren)

interface ArmorRouteRouteChildren {
  ArmorIdRoute: typeof ArmorIdRoute
  ArmorIndexRoute: typeof ArmorIndexRoute
}

const ArmorRouteRouteChildren: ArmorRouteRouteChildren = {
  ArmorIdRoute: ArmorIdRoute,
  ArmorIndexRoute: ArmorIndexRoute,
}

const ArmorRouteRouteWithChildren = ArmorRouteRoute._addFileChildren(
  ArmorRouteRouteChildren,
)

interface ConsumablesRouteRouteChildren {
  ConsumablesIdRoute: typeof ConsumablesIdRoute
  ConsumablesIndexRoute: typeof ConsumablesIndexRoute
}

const ConsumablesRouteRouteChildren: ConsumablesRouteRouteChildren = {
  ConsumablesIdRoute: ConsumablesIdRoute,
  ConsumablesIndexRoute: ConsumablesIndexRoute,
}

const ConsumablesRouteRouteWithChildren =
  ConsumablesRouteRoute._addFileChildren(ConsumablesRouteRouteChildren)

interface GemsRouteRouteChildren {
  GemsIdRoute: typeof GemsIdRoute
  GemsIndexRoute: typeof GemsIndexRoute
}

const GemsRouteRouteChildren: GemsRouteRouteChildren = {
  GemsIdRoute: GemsIdRoute,
  GemsIndexRoute: GemsIndexRoute,
}

const GemsRouteRouteWithChildren = GemsRouteRoute._addFileChildren(
  GemsRouteRouteChildren,
)

interface GripsRouteRouteChildren {
  GripsIdRoute: typeof GripsIdRoute
  GripsIndexRoute: typeof GripsIndexRoute
}

const GripsRouteRouteChildren: GripsRouteRouteChildren = {
  GripsIdRoute: GripsIdRoute,
  GripsIndexRoute: GripsIndexRoute,
}

const GripsRouteRouteWithChildren = GripsRouteRoute._addFileChildren(
  GripsRouteRouteChildren,
)

interface KeysRouteRouteChildren {
  KeysIdRoute: typeof KeysIdRoute
  KeysIndexRoute: typeof KeysIndexRoute
}

const KeysRouteRouteChildren: KeysRouteRouteChildren = {
  KeysIdRoute: KeysIdRoute,
  KeysIndexRoute: KeysIndexRoute,
}

const KeysRouteRouteWithChildren = KeysRouteRoute._addFileChildren(
  KeysRouteRouteChildren,
)

interface SigilsRouteRouteChildren {
  SigilsIdRoute: typeof SigilsIdRoute
  SigilsIndexRoute: typeof SigilsIndexRoute
}

const SigilsRouteRouteChildren: SigilsRouteRouteChildren = {
  SigilsIdRoute: SigilsIdRoute,
  SigilsIndexRoute: SigilsIndexRoute,
}

const SigilsRouteRouteWithChildren = SigilsRouteRoute._addFileChildren(
  SigilsRouteRouteChildren,
)

interface SpellsRouteRouteChildren {
  SpellsIdRoute: typeof SpellsIdRoute
  SpellsIndexRoute: typeof SpellsIndexRoute
}

const SpellsRouteRouteChildren: SpellsRouteRouteChildren = {
  SpellsIdRoute: SpellsIdRoute,
  SpellsIndexRoute: SpellsIndexRoute,
}

const SpellsRouteRouteWithChildren = SpellsRouteRoute._addFileChildren(
  SpellsRouteRouteChildren,
)

interface WeaponsRouteRouteChildren {
  WeaponsIdRoute: typeof WeaponsIdRoute
  WeaponsIndexRoute: typeof WeaponsIndexRoute
}

const WeaponsRouteRouteChildren: WeaponsRouteRouteChildren = {
  WeaponsIdRoute: WeaponsIdRoute,
  WeaponsIndexRoute: WeaponsIndexRoute,
}

const WeaponsRouteRouteWithChildren = WeaponsRouteRoute._addFileChildren(
  WeaponsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRouteRoute: AccessoriesRouteRouteWithChildren,
  ArmorRouteRoute: ArmorRouteRouteWithChildren,
  ConsumablesRouteRoute: ConsumablesRouteRouteWithChildren,
  GemsRouteRoute: GemsRouteRouteWithChildren,
  GripsRouteRoute: GripsRouteRouteWithChildren,
  KeysRouteRoute: KeysRouteRouteWithChildren,
  SigilsRouteRoute: SigilsRouteRouteWithChildren,
  SpellsRouteRoute: SpellsRouteRouteWithChildren,
  WeaponsRouteRoute: WeaponsRouteRouteWithChildren,
  MaterialGridRoute: MaterialGridRoute,
  MaterialsRoute: MaterialsRoute,
  CraftingIndexRoute: CraftingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
